/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfitness.formularios;

import sisfitness.models.UsuarioModel;

/**
 *
 * 
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

     private UsuarioModel usuarioLogeado;
     
  /**
     * @return the usuarioLogeado
     */
    public UsuarioModel getUsuarioLogeado() {
        return usuarioLogeado;
    }

    /**
     * @param usuarioLogeado the usuarioLogeado to set
     */
    public void setUsuarioLogeado(UsuarioModel usuarioLogeado) {
        this.usuarioLogeado = usuarioLogeado;
    }     
    
    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal( UsuarioModel usuarioLogeado) {
        initComponents();        
        this.usuarioLogeado=usuarioLogeado;
        Init();
        
    }
    
    private void Init()
    {
        setLocationRelativeTo(null);
        setTitle("Sistema Fitness...");
        if (usuarioLogeado!=null)
            infoUsuario.setText(usuarioLogeado.getLogin());
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        infoUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCategoria = new javax.swing.JMenuItem();
        mnuProducto = new javax.swing.JMenuItem();
        mnuCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRegistroVenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuReporteVenta = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Usuario: ");

        infoUsuario.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(infoUsuario))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jMenu1.setText("Mantenimiento");

        mnuCategoria.setText("Categoría");
        mnuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCategoria);

        mnuProducto.setText("Producto");
        mnuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProducto);

        mnuCliente.setText("Cliente");
        mnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        menuRegistroVenta.setText("Registro de Venta");
        menuRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroVentaActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegistroVenta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reporte");

        menuReporteVenta.setText("Reporte Venta");
        menuReporteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteVentaActionPerformed(evt);
            }
        });
        jMenu3.add(menuReporteVenta);

        jMenuBar1.add(jMenu3);

        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 268, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void mnuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriaActionPerformed
        // TODO add your handling code here:
            frmListaCategorias frm=new frmListaCategorias();
            frm.setVisible(true);
    }//GEN-LAST:event_mnuCategoriaActionPerformed

    private void mnuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductoActionPerformed
        // TODO add your handling code here:
            frmListaProductos frm=new frmListaProductos();
            frm.setVisible(true);        
    }//GEN-LAST:event_mnuProductoActionPerformed

    private void mnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteActionPerformed
        // TODO add your handling code here:
            frmListaClientes frm=new frmListaClientes();
            frm.setVisible(true);        
    }//GEN-LAST:event_mnuClienteActionPerformed

    private void menuRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroVentaActionPerformed
        // TODO add your handling code here:
            frmRegistraOrden frm=new frmRegistraOrden();
            frm.setVisible(true);          
    }//GEN-LAST:event_menuRegistroVentaActionPerformed

    private void menuReporteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteVentaActionPerformed
        // TODO add your handling code here:
         frmReporteOrden frm=new frmReporteOrden();
            frm.setVisible(true);             
    }//GEN-LAST:event_menuReporteVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuRegistroVenta;
    private javax.swing.JMenuItem menuReporteVenta;
    private javax.swing.JMenuItem mnuCategoria;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuProducto;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
