/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfitness.formularios;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import sisfitness.business.BCategoria;
import sisfitness.business.BProducto;
import static sisfitness.common.FuncionesGenericas.ConvertMayuscula;
import static sisfitness.common.FuncionesGenericas.esDecimal;
import static sisfitness.common.Parametros.OPCION_MODIFICAR;
import static sisfitness.common.Parametros.OPCION_NUEVO;
import sisfitness.models.CategoriaModel;
import sisfitness.models.ProductoModel;

/**
 *
 * 
 */
public class frmProducto extends javax.swing.JDialog {

 
    private String opcion;
    private boolean resultstatus=false;    
    private ProductoModel productoModel=new ProductoModel();
    
    BProducto bproducto=new BProducto();
    
    public frmProducto(java.awt.Frame parent, boolean modal, String opcion, ProductoModel productoModel) {
        super(parent, modal);
        this.opcion=opcion;
        this.productoModel=productoModel;
        initComponents();
        
        Init();
    }

    /**
     * @return the opcion
     */
    public String getOpcion() {
        return opcion;
    }

    /**
     * @param opcion the opcion to set
     */
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }
    
 /**
     * @return the resultstatus
     */
    public boolean isResultstatus() {
        return resultstatus;
    }

    /**
     * @param resultstatus the resultstatus to set
     */
    public void setResultstatus(boolean resultstatus) {
        this.resultstatus = resultstatus;
    }    
    
    /**
     * @return the productoModel
     */
    public ProductoModel getProductoModel() {
        return productoModel;
    }

    /**
     * @param productoModel the productoModel to set
     */
    public void setProductoModel(ProductoModel productoModel) {
        this.productoModel = productoModel;
    }    

    /**
     * Creates new form frmProducto
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cbxCategoria = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Categoría");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("Código");

        jToolBar1.setRollover(true);

        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);
        jToolBar1.add(jSeparator1);

        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        jLabel3.setText("Nombre");

        jLabel4.setText("Descripción");

        jLabel5.setText("Precio");

        jLabel6.setText("Stock");

        jLabel8.setText("Serie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre)
                        .addComponent(cbxCategoria, 0, 244, Short.MAX_VALUE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescripcion)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        ValidaCampos();
        
        CategoriaModel categoriaSelected = (CategoriaModel) cbxCategoria.getSelectedItem();        
        ProductoModel producto=new ProductoModel();
       
        if (opcion.equals(OPCION_MODIFICAR))
             producto.setId(productoModel.getId());
        
        producto.setNombre(txtNombre.getText());
        producto.setDescripcion(txtDescripcion.getText());
        producto.setSerie(txtSerie.getText());
        producto.setPrecio(Double.parseDouble(txtPrecio.getText()));
        producto.setStock(Double.parseDouble(txtStock.getText()));
        producto.setCategoria(categoriaSelected);
        
        int nResult=bproducto.GuardarProducto(opcion, producto);
        if (nResult>0)
        {
            if (opcion.equals(OPCION_NUEVO))
            {
                int nResultMsg =JOptionPane.showConfirmDialog(null, "Producto registrado!, ¿Desea continuar registrando productos?","Aviso",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                if (nResultMsg==JOptionPane.YES_OPTION)
                {
                    LimpiarCampos();
                }
                else
                {
                    this.resultstatus=true;
                    this.dispose();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El registro del producto fue actualizado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.resultstatus=true;
                this.dispose();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No fue posible registrar el producto", "Aviso", JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        ConvertMayuscula(evt);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void ValidaCampos()
    {
        boolean result=false;
        if (txtNombre.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Debe de ingresar el Nombre", "Aviso", JOptionPane.WARNING_MESSAGE);
        else if (txtSerie.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Debe de ingresar la Serie", "Aviso", JOptionPane.WARNING_MESSAGE);
        else if (txtPrecio.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Debe de ingresar el Precio", "Aviso", JOptionPane.WARNING_MESSAGE);   
        else if (txtStock.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Debe de ingresar el Stock", "Aviso", JOptionPane.WARNING_MESSAGE);    
        else if (!esDecimal(txtStock.getText()))
            JOptionPane.showMessageDialog(null, "Debe de ingresar un valor válido en el campo Stock", "Aviso", JOptionPane.WARNING_MESSAGE);
        else if (!esDecimal(txtPrecio.getText()))
            JOptionPane.showMessageDialog(null, "Debe de ingresar un valor válido en el campo Precio", "Aviso", JOptionPane.WARNING_MESSAGE);                       

    }
    
    private void LimpiarCampos()
    {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtSerie.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
    }
    
    private void Init()
    {
        setLocationRelativeTo(null);
        //
        txtCodigo.setEditable(false);

        //Carga Combo
        BCategoria bcategoria=new BCategoria();
        DefaultComboBoxModel<CategoriaModel> comboCategoria=new DefaultComboBoxModel<>();
        bcategoria.ListaCategoria().forEach(comboCategoria::addElement);
        cbxCategoria.setModel(comboCategoria);
        
        if (opcion.equals(OPCION_MODIFICAR))
        {
            //Cargamos la Información
            txtCodigo.setText(String.valueOf(productoModel.getId()));
            txtNombre.setText(productoModel.getNombre());
            txtDescripcion.setText(productoModel.getDescripcion());
            txtSerie.setText(productoModel.getSerie());
            txtPrecio.setText(String.valueOf(productoModel.getPrecio()));
            txtStock.setText(String.valueOf(productoModel.getStock()));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<CategoriaModel> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
