/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfitness.formularios;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import sisfitness.proxy.BOrdenVenta;
import sisfitness.common.exception.AccesoDenegadoException;
import sisfitness.common.SesionUsuario;
import sisfitness.formularios.tablas.OrdenVentaDetalleTableModel;
import sisfitness.models.ClienteModel;
import sisfitness.models.OrdenVentaDetalleModel;
import sisfitness.models.OrdenVentaModel;
import sisfitness.builder.ProductoModel;

/**
 *
 * 
 */
public class frmRegistraOrden extends javax.swing.JFrame {

    List<OrdenVentaDetalleModel> ListaDetalle=new ArrayList<>();
    OrdenVentaDetalleTableModel tablaDetalle;
    ClienteModel clienteSel=new ClienteModel();
    BOrdenVenta bOrdenVenta=new BOrdenVenta(SesionUsuario.getInstancia().getUsuario().getPerfil());
    /**
     * Creates new form frmRegistraOrden
     */
    public frmRegistraOrden() {
        initComponents();
        
        init();
    }
    
    private void init()
    {
        setLocationRelativeTo(null);
        setTitle("Registro de Ventas");
        
        txtTotal.setEditable(false);
        
        tablaDetalle=new OrdenVentaDetalleTableModel(ListaDetalle);
        
        gridDetalle.setModel(tablaDetalle);
        gridDetalle.getColumnModel().getColumn(0).setPreferredWidth(50);
        gridDetalle.getColumnModel().getColumn(1).setPreferredWidth(200);
        gridDetalle.getColumnModel().getColumn(2).setPreferredWidth(200);
        gridDetalle.getColumnModel().getColumn(3).setPreferredWidth(60);      
        gridDetalle.getColumnModel().getColumn(4).setPreferredWidth(60);    
        gridDetalle.getColumnModel().getColumn(5).setPreferredWidth(60);     
        gridDetalle.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);      
        
        tablaDetalle.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE || e.getType() == TableModelEvent.INSERT ) {
                     txtTotal.setText(String.valueOf( tablaDetalle.getTotal()));
                }
            }
        });
        
    }
    
    private void LimpiarCampos()
    {
        txtFecha.setText("");
        txtCliente.setText("");
        clienteSel=null;
        txtTotal.setText("0.00");
        tablaDetalle.Limpiar();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnRegistrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        btnBuscaCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridDetalle = new javax.swing.JTable();
        btnAddProducto = new javax.swing.JButton();
        btnRemoveProducto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Productos Vendidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(394, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jToolBar1.setRollover(true);

        btnRegistrar.setText("Registrar");
        btnRegistrar.setFocusable(false);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRegistrar);
        jToolBar1.add(jSeparator1);

        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        jLabel2.setText("Fecha Registro");

        jLabel3.setText("Cliente");

        txtFecha.setToolTipText("");

        btnBuscaCliente.setText("...");
        btnBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClienteActionPerformed(evt);
            }
        });

        gridDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(gridDetalle);

        btnAddProducto.setText("Agregar");
        btnAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductoActionPerformed(evt);
            }
        });

        btnRemoveProducto.setText("Quitar");
        btnRemoveProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductoActionPerformed(evt);
            }
        });

        jLabel4.setText("Total");

        txtTotal.setText("0.00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("(YYYY-MM-DD)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscaCliente))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAddProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemoveProducto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProducto)
                    .addComponent(btnRemoveProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       
        try {
            // TODO add your handling code here:
            ValidaCampos();
            //Añadimos informacion de la cabecera
            OrdenVentaModel ordenVentaModel=new OrdenVentaModel();
            ordenVentaModel.setFechaventa(txtFecha.getText());
            ordenVentaModel.setCliente(clienteSel);
            ordenVentaModel.setTotalventa(tablaDetalle.getTotal());
            ordenVentaModel.setOrdenVentaDetalles(tablaDetalle.Lista());
            
           int nResult= bOrdenVenta.setGuardar(ordenVentaModel);
           if (nResult>0)
           {
               int nResultMsg =JOptionPane.showConfirmDialog(null, "Se ha generado el Registro de Venta!, ¿Desea continuar registrando?","Aviso",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                if (nResultMsg==JOptionPane.YES_OPTION)
                {
                    LimpiarCampos();
                }
                else
                {
                    this.dispose();
                }           
           }  
        }catch (AccesoDenegadoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Restriccion", JOptionPane.WARNING_MESSAGE);
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
 

        /*
        ValidaCampos();

        CategoriaModel categoriaSelected = (CategoriaModel) cbxCategoria.getSelectedItem();
        ProductoModel producto=new ProductoModel();

        if (opcion.equals(OPCION_MODIFICAR))
        producto.setId(productoModel.getId());

        producto.setNombre(txtNombre.getText());
        producto.setDescripcion(txtDescripcion.getText());
        producto.setSerie(txtSerie.getText());
        producto.setPrecio(Double.parseDouble(txtPrecio.getText()));
        producto.setStock(Double.parseDouble(txtStock.getText()));
        producto.setCategoria(categoriaSelected);

        int nResult=bproducto.GuardarProducto(opcion, producto);
        if (nResult>0)
        {
            if (opcion.equals(OPCION_NUEVO))
            {
                int nResultMsg =JOptionPane.showConfirmDialog(null, "Producto registrado!, ¿Desea continuar registrando productos?","Aviso",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                if (nResultMsg==JOptionPane.YES_OPTION)
                {
                    LimpiarCampos();
                }
                else
                {
                    this.resultstatus=true;
                    this.dispose();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El registro del producto fue actualizado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.resultstatus=true;
                this.dispose();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No fue posible registrar el producto", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        */
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void ValidaCampos()
    {
        boolean result=false;
        if (txtFecha.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Debe de ingresar la Fecha", "Aviso", JOptionPane.WARNING_MESSAGE);
        else if (clienteSel==null)
            JOptionPane.showMessageDialog(null, "Debe seleccionar al Cliente", "Aviso", JOptionPane.WARNING_MESSAGE);
        else if (tablaDetalle.getRowCount()==0)
            JOptionPane.showMessageDialog(null, "Debe de ingresar Productos en la grilla", "Aviso", JOptionPane.WARNING_MESSAGE);   

    }
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClienteActionPerformed
        // TODO add your handling code here:
        frmBusquedaCliente frmcliente=new frmBusquedaCliente(this, rootPaneCheckingEnabled);
        frmcliente.setVisible(true);
        if (frmcliente.getClienteModelOutPut()!=null)
        {
            clienteSel=frmcliente.getClienteModelOutPut();
            txtCliente.setText(clienteSel.getDni() + " - " + clienteSel.getApellidos() + " " + clienteSel.getNombres());
        }
    }//GEN-LAST:event_btnBuscaClienteActionPerformed

    private void btnAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductoActionPerformed
        // TODO add your handling code here:
        frmBusquedaProducto frmproducto=new frmBusquedaProducto(this, rootPaneCheckingEnabled);
        frmproducto.setVisible(true);        
        if (frmproducto.getProductoSel()!=null)
        {
            addRow(frmproducto.getProductoSel());
        }
    }//GEN-LAST:event_btnAddProductoActionPerformed

    private void btnRemoveProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductoActionPerformed
        // TODO add your handling code here:
        int selectedRow = gridDetalle.getSelectedRow();
        if (selectedRow != -1) {
            tablaDetalle.removeItem(selectedRow);
            tablaDetalle.actualizarNroItems();
        }
    }//GEN-LAST:event_btnRemoveProductoActionPerformed

    private void addRow(ProductoModel productoSel)
    {
           int nItem=0;
            OrdenVentaDetalleModel item=new OrdenVentaDetalleModel();
            if (tablaDetalle.getRowCount()==0)
                nItem=1;
            else
                nItem=tablaDetalle.getRowCount() + 1;
              
            item.setProducto(productoSel);
            item.setItem(nItem);
            item.setCantidad(1);
            item.setPrecio(productoSel.getPrecio());         
            item.setTotal(item.getCantidad() * item.getPrecio());
            tablaDetalle.addItem(item);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProducto;
    private javax.swing.JButton btnBuscaCliente;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRemoveProducto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTable gridDetalle;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
